### ISSUE TITLE
iOS 14.2 keyWindow is always EKWindow

### ISSUE THREAD

**Issue by Jayxiang** [huri000/SwiftEntryKit#324] opened 2020-11-26 10:48 UTC
**Describe the bug**
In iOS 14.2 keyWindow is always EKWindow，but I tested it on 14.1, 13.7, and 11.4, no problem. 

**To Reproduce**
1. In your demo, `PresetsViewController` class，my test code in line 378：

```
            print(UIApplication.shared.keyWindow)
            SwiftEntryKit.dismiss() {
                print(UIApplication.shared.keyWindow)
            }
            SwiftEntryKit.display(entry: contentView, using: attributes)
``` 

**Expected behavior**
The keyWindow should be UIWindow

**Screenshots**
iOS 14.2：
<img width="449" alt="keyWindow" src="https://user-images.githubusercontent.com/12928482/100340898-d1128e00-3016-11eb-86ff-9e105895fde5.png">

iOS 11 13 14.1：
<img width="443" alt="UIWindow" src="https://user-images.githubusercontent.com/12928482/100341181-32d2f800-3017-11eb-9950-b29f972fb2d1.png">

**iPhone (please complete the following information):**
 - Device: [iPhone 12]
 - iOS Version: [iOS14.2]
 - Xcode Version [12.2]
 - Dependency Manager Version [CocoaPods 1.9.2]
 - SwiftEntryKit Release # [ 1.2.6]

**Additional context**
In addition, I want to put `dismissHandler`behind `didFinishDisplaying` in the `removeFromSuperview` method.

**Screenshots / Video Links**

**Comment by florin-saftoiu** [comment] 2020-12-03 15:02
I'm also seeing this, I was able to get around it by setting the main UIWindow as rollbackWindow when displaying :
`SwiftEntryKit.display(entry: myViewController, using: myAttributes, rollbackWindow: .custom(window: UIApplication.shared.keyWindow!))`

**Comment by JonathanChen123** [comment] 2020-12-14 08:09
I have the same issue on iOS14.2.

**Comment by RuttabHaroon** [comment] 2020-12-18 10:44
+1 I am having this issue in iOS14.2 but not in earlier versions

**Comment by hoangduoc0603** [comment] 2020-12-21 02:28
I have the same issue on iOS >= 14.2. Is there any update on this?? Thanks!!

**Comment by hoangduoc0603** [comment] 2020-12-21 02:30
> I'm also seeing this, I was able to get around it by setting the main UIWindow as rollbackWindow when displaying :
> `SwiftEntryKit.display(entry: myViewController, using: myAttributes, rollbackWindow: .custom(window: UIApplication.shared.keyWindow!))`

It does not work. What was your problem and what did you do?? Thanks!

**Comment by florin-saftoiu** [comment] 2020-12-21 10:07
> > I'm also seeing this, I was able to get around it by setting the main UIWindow as rollbackWindow when displaying :
> > `SwiftEntryKit.display(entry: myViewController, using: myAttributes, rollbackWindow: .custom(window: UIApplication.shared.keyWindow!))`
> 
> It does not work. What was your problem and what did you do?? Thanks!

After dismissing an entry, the entire  UI of the app was frozen. In the UI debugger I could see the keyWindow being of type EKWindow. For me the workaround works, but I should mention I'm on version 0.6.0 of SwiftEntryKit

**Comment by huri000** [comment] 2020-12-28 14:21
Hey @florin-saftoiu. This side effect is not caused by the same reason as the aforementioned issue's.
Generally, I'd consider what you're experiencing as a high priority issue, but since you mentioned using a super old release, I'd first recommend you to first take some time and update to `1.2.6`. Please report back in a separate issue, in more detail, if you're still having the same issue.

**Comment by huri000** [comment] 2020-12-28 15:17
@Jayxiang thanks for reporting this. This issue is now fixed. Please use `1.2.7`. 

Please see associated PR.
Changelog Reference: https://github.com/huri000/SwiftEntryKit/blob/master/CHANGELOG.md

**Closed by huri000** 2020-12-28 15:17 UTC
