### ISSUE TITLE
Issue on presenting UIViewController

### ISSUE THREAD

**Issue by omidgolparvar** [huri000/SwiftEntryKit#95] opened 2018-08-27 12:05 UTC
I use this code to present a `UIViewController`:

```swift
let vc = UIStoryboard(name: "Home", bundle: nil).instantiateViewController(withIdentifier: "VC") as! VC
SwiftEntryKit.display(entry: vc, using: .centerFloat)
```

But it does NOT work!!

- SwiftEntryKit 0.5.6

Do I have to do anything else?

**Comment by huri000** [comment] 2018-08-28 08:42
Possible duplicate of: [75](https://github.com/huri000/SwiftEntryKit/issues/75), [7](https://github.com/huri000/SwiftEntryKit/issues/7)
TL;DR - The height of your view is inferred from the constraints that applied to it. In case don't use Auto Layout, you need to explicitly set the contstraints by using `attributes.positionConstraints.`.

**Closed by huri000** 2018-08-28 08:42 UTC
