### ISSUE TITLE
Swift Compiler Warning about setters for isStatusBarHidden and statusBarStyle (deprecated in iOS 9.0)

### ISSUE THREAD

**Issue by dragosrobertn** [huri000/SwiftEntryKit#161] opened 2019-02-18 11:57 UTC
Using the latest version of SwiftEntryKit on a target that supports iOS10 and above, the Swift Compiler throws warning in regards to [UIApplication+EKAppearance.swift](https://github.com/huri000/SwiftEntryKit/blob/master/Source/Extensions/UIApplication%2BEKAppearance.swift) , when setting the isStatusBarHidden and statusBarStyle. 

```swift
    func set(statusBarStyle: EKAttributes.StatusBar) {
        let appearance = statusBarStyle.appearance
        UIApplication.shared.isStatusBarHidden = !appearance.visible
        UIApplication.shared.statusBarStyle = appearance.style
    }
```

1. Download and install SwiftEntryKit using CocoaPods
2. Click Build and Run to run the app
3. When building, Xcode will show 2 Buildtime warnings.

**Expected behavior**
No warnings should be shown. 

**Screenshots**

<img width="383" alt="screenshot 2019-02-18 at 11 42 16" src="https://user-images.githubusercontent.com/10534896/52948767-40534c80-3372-11e9-988e-fe260e7830d3.png">

**iPhone:**
 - Device: Any (But I used iPhone X, iPhone 7 Plus, iPhone 5s simulators and iPhone XS Max as real device)
 - iOS Version: iOS 12 (but the error is in regards to iOS 9).
 - Xcode Version 10.1
 - Dependency Manager Version:: CocoaPods 1.5.3
 - SwiftEntryKit Release # 0.8.8

**Additional context**
Solution for this can be @available that piece of code for iOS 9 and then leveraging UIViewController's `prefersStatusBarHidden` and `preferredStatusBarStyle` in the [EKRootViewController](https://github.com/huri000/SwiftEntryKit/blob/master/Source/Infra/EKRootViewController.swift) attributes as recommended by XCode. 

After writing this whole issue app I've noticed someone else https://github.com/huri000/SwiftEntryKit/pull/96 attempted to fix this, but they suggested removing functionality completely.

**Comment by huri000** [comment] 2019-02-26 20:01
Hi @dragosrobertn,
There are many iOS developers who are basing their project on a **none**-view-controller-based status bar appearance in iOS 9 (or any higher version) despite the deprecation warnings. 

I agree that your suggestion presents a much acceptable, encouraged and cleaner way of doing things.
But - please read [my response](https://github.com/huri000/SwiftEntryKit/pull/96#issuecomment-416494176) to #96. I would say the same in this case,

**Comment by huri000** [comment] 2019-03-09 20:14
Closing this as a duplicate of #96.
Manually setting the status bar visibility and style won't be removed for now.

**Closed by huri000** 2019-03-09 20:14 UTC
