### ISSUE TITLE
SwiftEntryKit Not Displaying Anything.

### ISSUE THREAD

**Issue by AndyIbanez** [huri000/SwiftEntryKit#271] opened 2020-01-29 18:33 UTC
Hi. I'm having this problem in which I'm trying to display somethig with SwiftEntryKit and nothing is being displayed. On top of it all the `SwiftEntryKit.isCurrentlyDisplaying` property is false immediately after calling `display`. Anyone know what's wrong?

My code looks like this:

```swift
    guard Biometrics.shared.biometricsAvailable() else { return }
    let availableBio = Biometrics.shared.availableBiometricString()
    
    var attributes = EKAttributes.bottomFloat
    attributes.position = EKAttributes.Position.bottom
    attributes.shadow = .active(with: .init(color: .black, opacity: 0.5, radius: 10, offset: .zero))
    
    if let touchIdPromptVc = UIStoryboard(name: "Authenticator", bundle: nil).instantiateViewController(withIdentifier: "touchIdPromptVc") as? TouchIDPromptViewController {
      touchIdPromptVc.biometricType = availableBio
      SwiftEntryKit.display(entry: touchIdPromptVc, using: attributes)
      print("CURRENTLY DISPLAYING")
      print(SwiftEntryKit.isCurrentlyDisplaying)
    }
```

The if-let is reached, and within it I try to display something with `SwiftEntryKit`, and immediately after I check if it's displaying something. I'm not sure if I'm doing something wrong here, but I can't find a reason for `display` to not do anything.

**Comment by vkhadyka** [comment] 2020-03-20 11:36
Have the same issue, although I pass view instead of view controller nothing displays.
How can I figure out it?

**Comment by ngocluan1192** [comment] 2020-04-06 13:11
I have the same issue

**Comment by hiteshsondhi88** [comment] 2020-05-16 13:12
Same here, tried the demo and it isn't working as well

**Comment by hiteshsondhi88** [comment] 2020-05-16 13:32
Okay, guys found the issue. Try this fork -> https://github.com/zhocker/SwiftEntryKit it works fine

**Comment by huri000** [comment] 2020-05-16 13:42
@hiteshsondhi88 not sure what you refer to as _the issue_, as the example project works as intended. You may just need to clear your cache and reinstall the library.

Try the following for CocoaPods dependency:
- Update cocoapods (`sudo gem install cocoapods`)
- Delete derived data's dir content.
- Clean project/build.
- `pod cache clean --all`
- `pod deintegrate`
- `pod install`
- Run the example project / side project

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-16 at 14 37 09](https://user-images.githubusercontent.com/5504255/82121154-ce3f0280-9782-11ea-9a9b-39f20fa6c010.png)

![Simulator Screen Shot - iPhone 8 - 2020-05-16 at 14 36 45](https://user-images.githubusercontent.com/5504255/82121151-cc753f00-9782-11ea-93f8-1972d70ad1b0.png)

**Comment by hiteshsondhi88** [comment] 2020-05-16 13:45
@huri000 try on dark mode

**Comment by hiteshsondhi88** [comment] 2020-05-16 13:47
@huri000 Check this commit https://github.com/zhocker/SwiftEntryKit/commit/34244f5ad102faa0075218c35c4c253d444b9f6b

**Comment by huri000** [comment] 2020-05-16 14:27
@hiteshsondhi88 same result. 
I don't recall a connection between the two - dark mode would only affect the styling regardless of the constraints.

@AndyIbanez 
Your original problem may have something to do w/ constraints not being set.
Also `isCurrentlyDisplaying` is synchronous while the display method is async - that would also explain why it prints false immediately after.

![Simulator Screen Shot - iPhone 8 - 2020-05-16 at 15 22 23](https://user-images.githubusercontent.com/5504255/82122048-12cd9c80-9789-11ea-9fea-a321c55d311d.png)

**Comment by huri000** [comment] 2020-08-31 11:07
Closing. please review the example project as well as previous comments. 
The issue is most likely due to unspecified constraints either in the attributes or the view.

**Closed by huri000** 2020-08-31 11:07 UTC
