### ISSUE TITLE
Pan Constraint Related Crash (iPad)

### ISSUE THREAD

**Issue by soumitra12** [huri000/SwiftEntryKit#228] opened 2019-09-03 13:34 UTC
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutYAxisAnchor:0x6000026e8c80 "SwiftEntryKit.EKContentView:0x7f9d740ea3c0.top"> secondAnchor:<NSLayoutYAxisAnchor:0x6000026eb340 "SwiftEntryKit.EKWrapperView:0x7f9d740e95a0.top">'

iPad 
 - Device: ipad Air2
 - iOS Version: iOS12
 - Xcode Version 10.2.1
 - Dependency Manager Version CocoaPods 1.75.0
 - SwiftEntryKit Release #226 

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutYAxisAnchor:0x6000026e8c80 "SwiftEntryKit.EKContentView:0x7f9d740ea3c0.top"> secondAnchor:<NSLayoutYAxisAnchor:0x6000026eb340 "SwiftEntryKit.EKWrapperView:0x7f9d740e95a0.top">'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011caa86fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011bedfac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011caa8482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000117290927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x0000000117497640 -[NSLayoutConstraint _setSymbolicConstant:constant:] + 672
	5   Foundation                          0x0000000117497881 -[NSLayoutConstraint setConstant:] + 68
	6   SwiftEntryKit                       0x0000000119e32bab $s13SwiftEntryKit13EKContentViewC26calculateLogarithmicOffset33_6CB2927F8AC112B77F158A7934BE9D41LL03forH018currentTranslationy12CoreGraphics7CGFloatV_AJtF + 587
	7   SwiftEntryKit                       0x0000000119e31ae0 $s13SwiftEntryKit13EKContentViewC20panGestureRecognized2grySo05UIPanG10RecognizerC_tF + 816
	8   SwiftEntryKit                       0x0000000119e3386c $s13SwiftEntryKit13EKContentViewC20panGestureRecognized2grySo05UIPanG10RecognizerC_tFTo + 60
	9   UIKitCore                           0x0000000124b1d14d -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	10  UIKitCore                           0x0000000124b25c69 _UIGestureRecognizerSendTargetActions + 109
	11  UIKitCore                           0x0000000124b235ba _UIGestureRecognizerSendActions + 311
	12  UIKitCore                           0x0000000124b22897 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 966
	13  UIKitCore                           0x0000000124b14c4e _UIGestureEnvironmentUpdate + 2820
	14  UIKitCore                           0x0000000124b14108 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 478
	15  UIKitCore                           0x0000000124b13e96 -[UIGestureEnvironment _updateForEvent:window:] + 200
	16  UIKitCore                           0x0000000124f6f5bc -[UIWindow sendEvent:] + 4057
	17  UIKitCore                           0x0000000124f4dd16 -[UIApplication sendEvent:] + 356
	18  Instabug                            0x000000011844e44b __IBGSwizzle_sendEvent + 224
	19  DocOn                               0x000000010f6856d1 -[DOApplication sendEvent:] + 113
	20  UIKitCore                           0x000000012501e293 __dispatchPreprocessedEventFromEventQueue + 3232
	21  UIKitCore                           0x0000000125020bb9 __handleEventQueueInternal + 5911
	22  CoreFoundation                      0x000000011ca0fbe1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x000000011ca0f463 __CFRunLoopDoSources0 + 243
	24  CoreFoundation                      0x000000011ca09b1f __CFRunLoopRun + 1231
	25  CoreFoundation                      0x000000011ca09302 CFRunLoopRunSpecific + 626
	26  GraphicsServices                    0x0000000120d922fe GSEventRunModal + 65
	27  UIKitCore                           0x0000000124f33ba2 UIApplicationMain + 140
	28  DocOn                               0x000000010f8da4cb main + 171
	29  libdyld.dylib                       0x000000011eb0a541 start + 1
	30  ???                                 0x0000000000000002 0x0 + 2

**Comment by huri000** [comment] 2019-09-03 13:53
@soumitra12 thanks for reporting this. I’ve never seen that one. to know the root cause I need to understand what exactly are you trying to do. Could you send over the code / alternately upload a small sample project that reproduces this? The logarithmic calculation seems correct. I can fix that by verifying the constant assigned is finite but I tend to think that something else went wrong here...

**Comment by soumitra12** [comment] 2019-09-04 09:43
Sure i will create a sample project and upload

**Comment by huri000** [comment] 2019-09-15 17:07
Hi @soumitra12, waiting on your feedback ^^
Could you provide additional details or upload an example project. I couldn't repro this one myself.

**Comment by huri000** [comment] 2019-10-07 08:32
This is dormant + couldn't reproduce. if it occurs to anyone else, I'll reopen it.
Closing for now.

**Closed by huri000** 2019-10-07 08:32 UTC
