### ISSUE TITLE
Screen freezes after dismissing the presented View which has a UITextView

### ISSUE THREAD

**Issue by AmrAbedal** [huri000/SwiftEntryKit#248] opened 2019-10-27 13:54 UTC
**Describe the bug**
Screen freezes after dismissing the presented View .

1 -  display the view 
2- try to edit text in text view
3- dismiss the view 
4- the screen will be freeze

**Comment by huri000** [comment] 2019-10-27 15:56
@amrObjection I need more information about your problem. Ideally, a small project that demonstrates it or an isolated code snippet that can be used.

**Comment by superk589** [comment] 2020-05-11 06:48
Same issue here, but a custom UITextField inside the entry.

**Comment by superk589** [comment] 2020-05-11 09:47
After some research, I confirm that the issue is caused by another framework, called CocoaDebug, which uses some swizzling methods that cause memory leaking.
EKWindow can't be released after dismissing and has a higher level than the main window.

**Comment by huri000** [comment] 2020-05-16 13:50
@superk589 that makes sense. another library tinkering w/ the window hierarchy may indeed cause that side effect as `SwiftEntryKit` assumes control over it when it displays its content. 

Important to mention that you can inject another window to go back to when the entry is dismissed. Please also see the API docs.
<img width="485" alt="Screenshot 2020-05-16 at 14 49 46" src="https://user-images.githubusercontent.com/5504255/82121383-81f4c200-9784-11ea-95fb-89de15dcc0ac.png">

**Comment by huri000** [comment] 2020-09-01 10:15
Closing as it seems like a side effect of window manipulation by another library.

**Closed by huri000** 2020-09-01 10:15 UTC
