### ISSUE TITLE
EKNotificationMessage has broken layout

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#64] opened 2018-06-27 07:18 UTC
**Describe the bug**
Seems there is a bug with EKNotificationMessage. See the different from example project with 0.5.1 and your gif example:

from gif example: ![toasts-48](https://user-images.githubusercontent.com/6259254/41958704-0d29d9ee-7a15-11e8-9610-851b09c04976.png)

from demo project: ![image](https://user-images.githubusercontent.com/6259254/41958515-7ceab236-7a14-11e8-87ae-68b261f82e5a.png)

Seems the labels should be slightly higher than now.
**iPhone (please complete the following information):**
 - Device: all
 - iOS Version: all
 - Xcode Version: 9.4.1
 - SwiftEntryKit Release #0.5.1

**Comment by Banck** [comment] 2018-06-27 07:20
And blur doesn't work in iOS 10.3.1 from your example:
![image](https://user-images.githubusercontent.com/6259254/41958770-37df0588-7a15-11e8-8a27-04fcd28ee877.png)

**Comment by huri000** [comment] 2018-06-27 07:28
> Seems there is a bug with EKNotificationMessage. See the different from example project with 0.5.1 and your gif example

This is not a bug, it is made by design. 
The gif was taken using iPhone X which includes the safe area insets. Correct me if I'm wrong but it seems that you are using smaller screen sized iPhone, this its insets are lower.

Thanks about the blur notice - I'll look into it. Could you please open another issue that is focused on it and close this one?

**Comment by Banck** [comment] 2018-06-27 07:31
iPhone x:
![image](https://user-images.githubusercontent.com/6259254/41959260-a3bf0df6-7a16-11e8-952f-c44ea909684c.png)
It doesn't look like on the gif. I Think it looks a bit ugly

**Comment by huri000** [comment] 2018-06-27 07:34
Still, it's not an issue in my opinion.
You can use with `EKAttributes`'s `positionConstraints` to tune the vertical offset of the view.

**Comment by huri000** [comment] 2018-06-27 07:37
I might add a top offset to the content of the message, it should solve your problem.

**Comment by Banck** [comment] 2018-06-27 07:38
Ok, but can't I raise the name label by 20 pixels and lower the description by 20 pixels?

**Comment by huri000** [comment] 2018-06-27 07:55
Currently, you can't. I'll enable more customizations in the next release.

**Comment by Banck** [comment] 2018-06-27 07:57
So then I should use xib view for that currently. Thanks :-)

**Comment by huri000** [comment] 2018-06-29 08:14
A fine tune has been added to your request on 0.5.3. Please see `EKNotificationMessage.Insets`.

**Closed by huri000** 2018-06-29 08:14 UTC
Labels: enhancement
