### ISSUE TITLE
Unable to install pod

### ISSUE THREAD

**Issue by leopic** [huri000/SwiftEntryKit#92] opened 2018-08-22 23:30 UTC
**Describe the bug**
Cocoapods errors out when trying to install SwiftEntryKit.

**To Reproduce**
1. Run `pod cache clean --all`
2. Run `pod deintegrate`
2. Add `pod 'SwiftEntryKit', '0.5.9'` into the Podfile 
2. Run `pod install`

**Expected behavior**
Pod would be installed without errors.

**Screenshots**
None, but this is the output:

```
$: pod install
Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
[!] Unable to find a specification for `SwiftEntryKit (= 0.5.9)`
```

**iPhone (please complete the following information):**
 - Device: N/A
 - iOS Version: N/A
 - Xcode Version 9.4.1
 - Dependency Manager Version CocoaPods 1.5.3
 - SwiftEntryKit Release 0.5.9

**Additional context**
I tried adding the pod without a version, then also tried using a previous version, to no avail.

Podfile looks more or less like this:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

target 'main' do
  pod 'Alamofire', '~> 4.5'
  pod 'wpxmlrpc'
  pod 'Kingfisher'
  pod 'SwiftyBeaver'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Auth0', '~> 1.0'
  pod 'SimpleKeychain', '~> 0.7'
  pod 'SwiftyRSA'
  pod 'AWSIoT', '~>2.6.0'
  pod 'DRPLoadingSpinner'
  pod 'SwiftEntryKit', '0.5.9'
end
```

Thanks!

EDIT: I just updated cocoapods to 1.5.3, same behavior

**Comment by huri000** [comment] 2018-08-23 11:33
Hi @leopic, 
Thanks for the elaborated description. Really weird issue. 
I'll try to reproduce this over the weekend and keep you posted.

**Comment by leopic** [comment] 2018-08-23 16:18
Much appreciated @huri000

**Comment by huri000** [comment] 2018-08-31 15:45
@leopic, Unfortunately, I cannot reproduce this issue you have been experiencing. Tried it on my machine and one other as well.
I've read that on some occasions `pod repo update` does the trick. But, that should work as the same  using a simple cache clean as you described. 
It is worth to give it a shot I say. Let me know if `pod repo update` works for you.

**Comment by huri000** [comment] 2018-09-06 20:02
It seems the scenario cannot be reproduced (by me and other installers). Please let me know if my previous suggestion worked for you. 
Anyway, I'm not convinced it is a SwiftEntryKit issue, more like a CocoaPods issue.
Therefore, I'm closing it for now.

**Closed by huri000** 2018-09-06 20:02 UTC
