### ISSUE TITLE
PopUp won't show in iPone X series

### ISSUE THREAD

**Issue by tiaramhdk8925** [huri000/SwiftEntryKit#272] opened 2020-02-04 07:48 UTC
hi, i found a problem using this library. this library works really well on iPhone 7, but when i try to run my app on iPhone X series the pop up won't show up  like nothing happened but i can't click other button like freezing. 

i tried to debug it on X series, when i try to call SwiftEntryKit.display(entry: popUpView, using: AttributedDialog.myAttribute()) the display func stopped at line 206 
entryVC.configure(entryView: entryView) (EKWindowProvider.swift). 

it didn't call : 
self.entryView = entryView
self.rollbackWindow = rollbackWindow

but when i used iphone 7 it calls both lines above.

 - Device: X series
 - iOS Version: [13.2.2]
 - Xcode Version [11.2.1]
 - SwiftEntryKit Release # [1.2.3]

thank you.

**Comment by huri000** [comment] 2020-02-04 08:18
Hi @tiaramhdk8925,
Could you upload a small project with which the problem can be reproduced?
I’d try to repro later today myself.

**Comment by tiaramhdk8925** [comment] 2020-02-05 09:59
Hi @huri000 i was trying to make the small project you requested, but it ended up can't represent the reproduction of the bug idk if it's because it's just "small project". is it about to memory usage thing? 

btw i tried to debug it once again my app, and it actually stopped at 
animateIn()  when initialize `let animation = attributes.entranceAnimation` [EKContentView line 381]
and it's all happening to all popup that i implement in the app

btw this is the code that i used for the popup

```
class ViewController: UIViewController{
private func popupLogout() {
        let v = DialogLogView()
        v.delegate = self
        SwiftEntryKit.display(entry: v, using: AttributedPopUp.attribute2())
 }
}

class AttributedPopUp {
    static func attribute() -> EKAttributes {
        var attributes = EKAttributes()
        attributes.statusBar = .light
        attributes.position = .center
        attributes.windowLevel = .normal
        attributes.displayDuration = .infinity
        attributes.entryInteraction = .absorbTouches
        attributes.screenInteraction = .absorbTouches
        attributes.entranceAnimation = .init(translate: .init(duration: 0.7, spring: .init(damping: 0.7, initialVelocity: 0)), scale: .init(from: 0.7, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)))
        attributes.scroll = .disabled
        attributes.hapticFeedbackType = .success
        attributes.screenBackground = .color(color: .init(UIColor.fBlur))
        
        return attributes
    }
}

```

**Comment by tiaramhdk8925** [comment] 2020-02-06 03:49
hi @huri000 i think this problem is related to https://github.com/huri000/SwiftEntryKit/issues/255 

when i read the issue it happened exactly like the issue 255 described. but finally for now my team can figure it out by clearing some codes and fixing the program flow in our app. i assumed that this is memory issue. 

hopefully anyone could figure out how to fix this besides clearing some codes.

thank you

**Comment by huri000** [comment] 2020-08-31 11:35
Closing for now as I couldn't reproduce. If the issue persists please let me know.

**Closed by huri000** 2020-08-31 11:35 UTC
