### ISSUE TITLE
Crash displaying basic entry

### ISSUE THREAD

**Issue by ivancr** [huri000/SwiftEntryKit#122] opened 2018-10-05 16:44 UTC
**Describe the bug**
App crashes trying to display anything.

I'm testing your usage example for custom view: https://github.com/huri000/SwiftEntryKit#presets-usage-example

**To Reproduce**
Create a button that runs this code when tapped: https://github.com/huri000/SwiftEntryKit#presets-usage-example

**Expected behavior**
Not crashing

**Screenshots**
![screen shot 2018-10-05 at 12 27 53](https://user-images.githubusercontent.com/8583018/46547574-52888e80-c89a-11e8-861a-41b9081c95f7.png)

**iPhone (please complete the following information):**
Xcode 10
- iPad Pro 10.5" Simulator running iOS 11.4 and iOS 12
- iPhone XS Simulator running iOS 11.4 and iOS 12
- iPad mini running iOS 11.3
 - iOS Version: [e.g. iOS9.3]
 - Xcode 10
 - Dependency Manager Version CocoaPods 1.5.3
 - SwiftEntryKit Release # 0.8.2

**Comment by huri000** [comment] 2018-10-05 17:17
Hi - Can you see the stack trace using an exception breakpoint? Tried that snippt to make sure but couldn't reproduce any crash.

**Comment by ivancr** [comment] 2018-10-08 13:53
That was it! Thanks so much!

**Comment by huri000** [comment] 2018-10-08 14:10
Gladly! Closing the issue now.

**Closed by huri000** 2018-10-08 14:10 UTC
