### ISSUE TITLE
SwiftEntryKit EKAttributes crash

### ISSUE THREAD

**Issue by iRemark** [huri000/SwiftEntryKit#219] opened 2019-08-13 06:00 UTC
**Screenshots / Video Links**
![70899B23-0218-4B58-97E9-3DA1CF821EB9](https://user-images.githubusercontent.com/12713866/62918511-66fab900-bdd2-11e9-9cc1-128785bee514.png)

Xcode 10.2.1 
iOS 12.3.1
SwiftEntryKit (1.1.1) [swift 5]

Please help me ...      o(╥﹏╥)o

**Comment by huri000** [comment] 2019-08-13 06:24
I think the cause might be some old cached pod version.

Can you try the following?
- Update cocoapods (`udo gem install cocoapods`)
- Delete derived data dir content.
- Clean project/build.
- `pod cache clean --all`
- `pod deintegrate`
- `pod install`

**Comment by huri000** [comment] 2019-08-13 06:39
@iRemark 
Just to make sure, I tested this on this project. Things seem to be in order...
[stuff.zip](https://github.com/huri000/SwiftEntryKit/files/3495590/stuff.zip)

Let me know if the steps above didn't help.

**Comment by HackShitUp** [comment] 2019-08-14 21:18
@huri000 the solution you provided fails. I'm getting the same crash as @iRemark.

Specifically, I think it happens whenever we try to add an image in the EKTextField. 

<img width="521" alt="EK" src="https://user-images.githubusercontent.com/14321808/63057100-71db4980-beb7-11e9-92de-29c24f18bab4.png">


My code:

<img width="975" alt="Screen Shot 2019-08-14 at 5 17 10 PM" src="https://user-images.githubusercontent.com/14321808/63057111-77389400-beb7-11e9-890f-936c196285fa.png">

**Comment by huri000** [comment] 2019-08-14 21:36
Thanks, @HackShitUp, though I don't think @iRemark's issue is related to this. A hotfix will be released in a few moments.

**Comment by HackShitUp** [comment] 2019-08-14 21:43
@huri000 Yup, my mistake! Also, sorry for the blurry screenshot. Just so you know the error message was related to something like
```
Unexpectedly found nil while unwrapping an optional value...
```

I commented out that ```if let ``` in your code, but the crash still occurred.

**Comment by huri000** [comment] 2019-08-14 21:55
Hotfix available (`1.1.2`) 🎉 
@HackShitUp thanks again for reporting this. let me know if that works for you.

**Comment by HackShitUp** [comment] 2019-08-14 22:16
@huri000 
It's still crashing :/. Now, it's crashing during the *EKFormMessageView* initialization. Here's the full report:
```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

Steps Leading to Crash:
1. Selector method from a UIButton subclass.
2. Method calls this static function for a static class (NGAlertManager — adopts SwiftEntryKit). The function sends a reset password link via this method:
```
    /// Reset the current user's password.
    static func resetPassword() {
        // Ensure that there are no currently displaying entries at the moment
        guard SwiftEntryKit.isCurrentlyDisplaying == false else {
            return
        }
        
        // MARK: - SwiftEntryKit
        var attributes = EKAttributes.centerFloat
        attributes.hapticFeedbackType = .success
        attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 8, offset: .zero))
        attributes.screenInteraction = .dismiss
        attributes.entryInteraction = .absorbTouches
        attributes.scroll = .enabled(swipeable: true, pullbackAnimation: .jolt)
        attributes.roundCorners = .all(radius: 14)
        attributes.entranceAnimation = .init(translate: .init(duration: 0.7, spring: .init(damping: 0.7, initialVelocity: 0)), scale: .init(from: 0.7, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.2))
        attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.35)))
        attributes.screenBackground = EKAttributes.BackgroundStyle.color(color: EKColor(UIColor.black.withAlphaComponent(0.30)))
        attributes.entryBackground = EKAttributes.BackgroundStyle.color(color: .white)
        attributes.positionConstraints.size = .init(width: .offset(value: 32), height: .intrinsic)
        attributes.positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 20, screenEdgeResistance: 8))
        attributes.statusBar = .currentStatusBar
        attributes.displayDuration = .infinity
        
        // Setup the placeholder label
        let placeholder = EKProperty.LabelContent(text: "What's your email?", style: .init(font: UIFont.demibold(15), color: EKColor(.lightGray), alignment: .left))
        // Setup the text field image icon
        let emailIcon = UIImage(named: "Email")!
        
        // Setup the text field
        let textField = EKProperty.TextFieldContent(keyboardType: .default, placeholder: placeholder, textStyle: .init(font: .medium(17), color: .black), isSecure: false, leadingImage: emailIcon, bottomBorderColor: EKColor(.groupTableViewBackground))
        
        // Alert Title
        let title = EKProperty.LabelContent(text: "Reset Password", style: .init(font: UIFont.demibold(17), color: .black, alignment: .center))
        
        // Alert Action Button
        let doneButton = EKProperty.ButtonContent(label: .init(text: "Done", style: .init(font: UIFont.heavy(15), color: EKColor(.babyBlue))), backgroundColor: .clear, highlightedBackgroundColor: EKColor(.groupTableViewBackground)) {
          // Send a password link to email via EKProperty.TextFieldContent's 'textField' attribute
        }
        
        // Display the form message view
        let contentView = EKFormMessageView(with: title, textFieldsContent: [textField], buttonContent: doneButton)
        SwiftEntryKit.display(entry: contentView, using: attributes)
    }
```

**Comment by huri000** [comment] 2019-08-14 22:41
Updating to `1.1.2` from `1.1.1`, I managed to reproduce this. There was no apparent logical reason for the crash, so I cleaned the build `Cmd + Shift + K` and it had worked properly after that. To me, it seems to be a CocoaPods caching issue. Here is the sample project with your code:

[stuff 2.zip](https://github.com/huri000/SwiftEntryKit/files/3503601/stuff.2.zip)

**Comment by HackShitUp** [comment] 2019-08-14 23:56
@huri000 you're right, this seemed to be an issue with my pods caching previous builds! Thanks for the help 👍

**Comment by huri000** [comment] 2019-08-18 11:55
@iRemark please view my [response](https://github.com/huri000/SwiftEntryKit/issues/219#issuecomment-520705548). 
I'm assuming this was resolved. let me know otherwise.

**Closed by huri000** 2019-08-18 11:55 UTC
