### ISSUE TITLE
Initialise ButtonBarContent using [ButtonContent] rather than ButtonContent...

### ISSUE THREAD

**Issue by NiallKiddle** [huri000/SwiftEntryKit#187] opened 2019-05-23 19:34 UTC
I tried to fork this but got an exception when running. For my use case I have created a controller class to handle different types of prebuilt alerts that can then be called withinin the project easily. I would basically like to be able to pass in an array of ButtonContents and initialise ButtonBarContent using that.

The initialise method expects ButtonContent... rather than [ButtonContent]. I'm not entirely sure of the reason for doing this or if there is potentially some clarification I could get on how I may get around this.

The reason I am doing this is so that I can call a function that has a completion handler for the button action which can be called from anywhere inside the project.

Here is the method of what I am trying to do in my controller class.
<img width="1078" alt="Screenshot 2019-05-23 at 20 34 34" src="https://user-images.githubusercontent.com/32180688/58281112-3b030500-7d9a-11e9-9777-87ce848276b4.png">

**Comment by huri000** [comment] 2019-05-23 19:58
Hi @NiallKiddle,
The current initializer expects a variadic parameter, not an array. That is what troubles the compiler.
As a solution, I would suggest exposing another initializer and transferring the current initializer's logic to it. In addition, the current initializer (the one accepting the variadic button content) should call the new initializer to initialize everything.
I will be able to make that change tomorrow or the next day, but if you want, you can pull request.

**Comment by NiallKiddle** [comment] 2019-05-25 07:03
I have created a pull request to merge the changes into the master branch.

The second init method did actually solve the issue and can ButtonBarContent can now be initialised using an array as well as variadic of ButtonContent

**Comment by huri000** [comment] 2019-05-28 10:57
Thanks, @NiallKiddle!
That change will be released with `5.0.1` in the next few days.
Cheers!

**Comment by mojtaba-almoussawi** [comment] 2019-06-16 17:57
I can see a commit on Apr 3 that add the initializer, but the issue is still there. 
This initializer that accept an array is not exist! Note: i have updated to the latest version `1.0.1`
Also the code is already there in the repo with the new init method. But i don't know where the problem is. 
So far i have used:

**Comment by NiallKiddle** [comment] 2019-06-16 18:00
@huri000 has not yet released version 1.0.5 containing the fix yet.

For now you can point the pod to use my git fork at:
`pod 'SwiftEntryKit', :git => 'https://github.com/NiallKiddle/SwiftEntryKit`

**Comment by mojtaba-almoussawi** [comment] 2019-06-16 18:04
@NiallKiddle but it's merged right? 
[Merge pull request #188 from NiallKiddle/master](https://github.com/huri000/SwiftEntryKit/commit/5b8f6fc71db26f11c8a4d39cc3ff01719f8cc1ae?diff=unified)

**Comment by huri000** [comment] 2019-06-16 18:42
Apologies for the delay. `1.0.2` has been released just now.

**Closed by huri000** 2019-06-16 18:42 UTC
Labels: enhancement
