### ISSUE TITLE
iOS 13 devices crash somtimes v1.2.3

### ISSUE THREAD

**Issue by pikacode** [huri000/SwiftEntryKit#298] opened 2020-08-25 05:24 UTC
**SwiftEntryKit Release**
 1.2.3
 
**Describe the bug**
crash only on iOS 13 devices when EKWindow init
```
Fatal Exception: NSInvalidArgumentException
-[UIApplication connectedScenes]: unrecognized selector sent to instance 0x153e645d0
```

**Screenshots**
crash stack:
 
![企业微信截图_361a8219-e438-49c9-a1de-031d4ee97718](https://user-images.githubusercontent.com/12589575/91119731-8eaf7d00-e6c6-11ea-859c-0198408cc36e.png)

devices info:
![企业微信截图_d80d0e92-e0e6-4564-a324-34f82c15103b](https://user-images.githubusercontent.com/12589575/91119449-c2d66e00-e6c5-11ea-814f-706ac5fe02df.png)
 
maybe add the code in init method for iOS 13 could resolve this? :
```
if UIApplication.shared.responds(to: #selector(getter: UIApplication.connectedScenes)) {
}
```

**Comment by huri000** [comment] 2020-08-25 07:02
Would be interesting to know the state of the app at the time of the crash, as well as how common the crash is. It seems like the method connectedScenes is missing.

I'll try to look into this later this today or tomorrow.

**Comment by huri000** [comment] 2020-08-31 11:25
Revisiting it again, I'm not too sure that adding `if UIApplication.shared.responds(to: #selector(getter: UIApplication.connectedScenes)) {}` won't be causing other unwanted effects that cannot be monitored - such as not showing anything. Need to investigate further and think about it as I couldn't reproduce the issue so far.

**Comment by pikacode** [comment] 2020-09-10 03:16
It seems that the crash happened when the `display` method was called a lot of times in a very short period. When our App disconnects from the network, all of the requests failed and we use EKit to display the errors.

**Comment by huri000** [comment] 2020-12-28 15:21
Closing. I'm suggesting to throttle invocations in such cases.

**Closed by huri000** 2020-12-28 15:21 UTC
