### ISSUE TITLE
Displaying Popup Alert with attributes is crashing

### ISSUE THREAD

**Issue by idevChandra6** [huri000/SwiftEntryKit#269] opened 2020-01-10 00:33 UTC
**Describe the bug**
Displaying Popup Alert with attributes is crashing on iPhone X and iPhone 11 Pro  

**To Reproduce**
Please have this below code in viewDidAppear(_:) and see if it crashes.
All the values that are assigned are no-nils.
```
        var attributes: EKAttributes!
        attributes = .topNote
        attributes.displayDuration = 3
        attributes.shadow = .active(with: .init(color: .black, opacity: 0.5, radius: 10, offset: .zero))
        attributes.popBehavior = .animated(animation: .translation)
        attributes.entryBackground = .color(color: EKColor(light: .darkGray, dark: .darkGray))
        attributes.statusBar = .inferred
        attributes.displayMode = .inferred

        let style = EKProperty.LabelStyle(font: UIFont(name: "Helvetica", size: 13)!, color: EKColor(light: .red, dark: .red))
        let labelContent = EKProperty.LabelContent(text: "This is description", style: style)
        let image = UIImage(named: "AddFavor")
        let imageContent = EKProperty.ImageContent(image: image!, size: CGSize(width: 20, height: 20))
        
        let contentView = EKImageNoteMessageView(with: labelContent, imageContent: imageContent)
        
        SwiftEntryKit.display(entry: contentView, using: attributes)

```
**Expected behavior**
The code crashes at last line.

**Screenshots**
<Not Applicable>

**iPhone (please complete the following information):**
 - Device: iPhone X, iPhone 11 Pro
 - iOS Version: iOS 13.2
 - Xcode Version:  11.3 (11C29)
 - Dependency Manager Version : CocoaPods 1.8.3
 - SwiftEntryKit Release # 1.2.3

**Additional context**
NA

**Screenshots / Video Links**
NA

**Comment by huri000** [comment] 2020-01-10 09:06
I couldn't repro this. I suspect it's a cached pod issue. Could you please try [this](https://github.com/huri000/SwiftEntryKit/issues/259#issuecomment-556977529).
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-10 at 09 03 18](https://user-images.githubusercontent.com/5504255/72140321-6ddd2600-3388-11ea-94dd-7ed9e5300047.png)

**Comment by idevChandra6** [comment] 2020-01-12 23:31
Hi Huri, I tried as you said above.
It did not solve.

I observed this. Please check.

```
/* var attribues = EKAttributes() This line crashes. Not sure why. This crashes on iOS 12.*, 13.* */
var attributes: EKAttributes! // This line and next line does not crash.
attributes = .topNote
attributes.displayDuration = 4.0
attributes.shadow = .active(with: .init(color: .black, opacity: 0.5, radius: 10, offset: .zero))
attributes.popBehavior = .animated(animation: .translation)
attributes.entryBackground = .color(color: EKColor(light: .darkGray, dark: .darkGray))
attributes.statusBar = .inferred
attributes.displayMode = .inferred

let style = EKProperty.LabelStyle(font: UIFont(name: "Helvetica", size: 13)!, color: EKColor(light: .red, dark: .red))
let labelContent = EKProperty.LabelContent(text: "This is description", style: style)
let imageContent = EKProperty.ImageContent(image: UIImage(named: "AddFavor")!, size: CGSize(width: 20, height: 20))
        
let contentView = EKImageNoteMessageView(with: labelContent, imageContent: imageContent)
        
SwiftEntryKit.display(entry: contentView, using: attributes) // Crashes here

```

I am setting  `displayDuration` as `4.0`. But it is set to 2.0 when I inspect. Please see the below variable inspect information - SwiftEntryKit.EKAttributes.DisplayDuration.
 
```
attributes	SwiftEntryKit.EKAttributes	
name	String?	nil	none
position	SwiftEntryKit.EKAttributes.Position	top
precedence	SwiftEntryKit.EKAttributes.Precedence	override
displayDuration	SwiftEntryKit.EKAttributes.DisplayDuration	2
positionConstraints	SwiftEntryKit.EKAttributes.PositionConstraints	
screenInteraction	SwiftEntryKit.EKAttributes.UserInteraction	
entryInteraction	SwiftEntryKit.EKAttributes.UserInteraction	
scroll	SwiftEntryKit.EKAttributes.Scroll	enabled
hapticFeedbackType	SwiftEntryKit.EKAttributes.NotificationHapticFeedback	none
lifecycleEvents	SwiftEntryKit.EKAttributes.LifecycleEvents	
displayMode	SwiftEntryKit.EKAttributes.DisplayMode	inferred
entryBackground	SwiftEntryKit.EKAttributes.BackgroundStyle	<invalid> (0x20)
screenBackground	SwiftEntryKit.EKAttributes.BackgroundStyle	visualEffect
shadow	SwiftEntryKit.EKAttributes.Shadow	active
roundCorners	SwiftEntryKit.EKAttributes.RoundCorners	none
border	SwiftEntryKit.EKAttributes.Border	none
statusBar	SwiftEntryKit.EKAttributes.StatusBar	inferred
entranceAnimation	SwiftEntryKit.EKAttributes.Animation	
exitAnimation	SwiftEntryKit.EKAttributes.Animation	
popBehavior	SwiftEntryKit.EKAttributes.PopBehavior	animated
```

**Comment by huri000** [comment] 2020-01-12 23:51
I just tried now; Couldn't reproduce. The entry displays for 4 seconds as assigned to `displayDuration`. No crash occurred. I do believe that if it had normally crashed, it would have happened to quite a lot of devs who use this library.
Lemme ask you this. Have you tried looking at the samples inside the example project? are they working for you?

Please make sure you run through these steps again, then, please run a side project w/ the example you posted:

- Update cocoapods (`sudo gem install cocoapods`)
- Delete derived data dir content.
- Clean project/build.
- `pod cache clean --all`
- `pod deintegrate`
- `pod install`
- Run the example project / side project

**Comment by idevChandra6** [comment] 2020-01-14 06:02
Changing my project code to Swift 5.0 solved the problem. It took time though. Worth the effort.
This also made the crash stopped for
`var attributes = EKAttributes()`

Thanks much for great library Huri.

**Closed** 2020-01-16 04:35 UTC
